AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: PII replacement service

Parameters:
  SourceBucketName:
    Type: String
  DestinationBucketName:
    Type: String

Resources:
  ## S3 bucket
  SourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref SourceBucketName    
  DestinationBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref DestinationBucketName   

  PIIExtractionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: start-pii-extraction/
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref SourceBucketName
        - S3CrudPolicy:
            BucketName: !Ref DestinationBucketName
      Environment:
        Variables:
          SOURCE_BUCKETNAME: !Ref SourceBucketName
          DESTINATION_BUCKETNAME: !Ref DestinationBucketName 
          COMPREHEND_ROLE: arn:aws:iam::257967673968:role/service-role/AmazonComprehendServiceRole-PII2
          # DOCUMENT_ANALYIS_COMPLETED_SNS_TOPIC_ARN:
          #   !Sub
          #   - arn:aws:sns:${AWS::Region}:${AWS::AccountId}:${AWS::StackName}-${TopicName}
          #   - { TopicName: DocumentAnalysisCompleted }
          # TEXTRACT_PUBLISH_TO_SNS_ROLE_ARN:
          #   !Sub
          #   - arn:aws:iam::${AWS::AccountId}:role/${AWS::StackName}-${RoleName}
          #   - { RoleName: TextractPublishToSNSTopicRole }
          # PROVISION_NAME: claims-venue-attorney-characteristics
          # CLAIM_CHARACTERISTICS_FILE: s3://claimslens-characteristics/claim_characteristics.tsv
      # Events:
        # ClaimsVenueAttorneyCharacteristicsApi:
        #   Type: Api
        #   Properties:
        #     RestApiId: !Ref ClaimLensDocLensAIApiGateway
        #     Path: /claims-venue-attorney-characteristics
        #     Method: POST
      FunctionName:
        !Sub
        - ${AWS::StackName}-${LambdaFunctionName}
        - { LambdaFunctionName: PIIExtractionFunction }
      Handler: app.lambda_handler
      # Role:
      #   !GetAtt
      #   - StartDocumentAnalysisFunctionLambdaExecutionRole
      #   - Arn
      MemorySize: 128
      Runtime: python3.9
      Timeout: 30

  ## Lambda function
  ComprehendPIIResultsFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: comprehend-results-processor
      Handler: app.lambda_handler
      Runtime: python3.9
      MemorySize: 512
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref SourceBucketName
        - S3CrudPolicy:
            BucketName: !Ref DestinationBucketName
      Environment:
        Variables:
          SOURCE_BUCKETNAME: !Ref SourceBucketName
          DESTINATION_BUCKETNAME: !Ref DestinationBucketName             
      Events:
        ComprehendResultsAvailable:
          Type: S3
          Properties:
            Bucket: !Ref DestinationBucket
            Events: s3:ObjectCreated:*
            Filter: 
              S3Key:
                Rules:
                  - Name: prefix
                    Value: 'output/' 
                  - Name: suffix
                    Value: '.out'    
Outputs:
  SourceBucketName:
    Value: !Ref SourceBucketName
    Description: S3 Bucket for object storage
  DestinationBucketName:
    Value: !Ref DestinationBucketName
    Description: S3 destination Bucket for object storage